#! /bin/sh

### BEGIN INIT INFO
# Provides:          ipv6mon
# Required-Start:    $syslog $network
# Required-Stop:     $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IPv6 Address Usage Monitoring Daemonn
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/ipv6mon
NAME=ipv6mon
DESC='IPv6 Address Monitoring Daemon'
CONFIGFILE=/etc/ipv6mon.conf
LOCKFILE=/var/run/ipv6mon.pid
OPTIONS="-v -c $CONFIGFILE"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	
	if $DAEMON $OPTIONS;then
	  echo "$NAME."

	else
	  echo "failed"
	fi

	;;
  stop)
	echo -n "Stopping $DESC: "
	if kill `cat $LOCKFILE` 2>/dev/null; then
		echo "$NAME."
	else
		echo "failed." && exit 1
	fi
	;;

  restart)
	echo "Restarting $DESC: "

	echo -n "Stopping $DESC: "
	if kill `cat $LOCKFILE` 2>/dev/null; then
		echo "$NAME."
	else
		echo "failed." && exit 1
	fi

	echo -n "Starting $DESC: "
	
	if $DAEMON $OPTIONS;then
	  echo "$NAME."
	else
	  echo "failed"
	fi

	;;
  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
